### PR TITLE
Updated the reference of crypto/pbkdf2 to its new home at golang.org/x/crypto/pbkdf2

### PR DESCRIPTION
**Pull request by erans**

### CODE REVIEW

**Comment by kitcambridge** [comment]
Thank you!

**Comment by erans** [comment]
You are most welcome. You don't know by any chance of a Go based Oz (https://github.com/hueniverse/oz) implementation?

**Comment by kitcambridge** [comment]
I don't, sorry. :disappointed: I saw you created a repo, though! Would love to collaborate on an implementation, if you have the time and inclination.

**Comment by erans** [comment]
Would love to collaborate. Once I have a few basic things I'll push it and
we can start doing some work together.

I'm still rather new to Go so I'm not always clear about the proper "Go"
ways of doing things. But I'm quick learner :-)

Eran

**Comment by kitcambridge** [comment]
Awesome! I've only worked on a couple of Go projects, so it should be a fun learning experience.

**Pull request merged**
